### ISSUE TITLE
Turbo Router firing multiple requests on data-request

### ISSUE THREAD

**Issue by philipbelcher** [octobercms/ajax#12]
Hi guys.

Loving the Turbo Router but I have a weird situation whereby if I navigate between multiple pages and then trigger a form using `data-request` it seems to fire the request multiple times. It seems exponential too - so if I start on the page with the Form and trigger it, it correctly fires once. If I start on a different page, navigate to the page with the Form and trigger it, it fires twice. Navigate twice before firing and it fires 4 times etc etc.

When I add the meta tag to disable the turbo route (`<meta name="turbo-visit-control" content="disable" />`) the Form correctly only ever fires once, no matter how much I navigate.

Is there a bug or have I missed something fundamental with how Turbo Router works? Many thanks

Version: 3.0.62

**Comment by samgeorges** [comment]
Hey @philipbelcher 

Thanks for reporting this. I was able to replicate it by including the framework twice on the page. This would happen if the framework was passed through the combiner.

It should be fixed by 220a13032727398d837471c6eee34959a66d64b6 and available in the next patch release of OCMS (>=v3.0.63)
