### ISSUE TITLE
404 pages strange behavior with turbo router

### ISSUE THREAD

**Issue by acasar** [octobercms/ajax#22]
We noticed some some strange behavior when navigating to a 404 page using a turbo router.

1. the page blinks. It looks like it looses its CSS styling for a fraction of a second, which is strange, since the same stylesheet is used for both pages.
2. javascript is behaving strangely (some events are applied twice while some event listeners from previous pages are lost)

This is a short video of the problem on a default OctoberCMS installation, but we noticed the same issues on our custom themes too:

https://user-images.githubusercontent.com/6329543/225606737-93717349-6462-4526-aae1-029a727fd62a.mp4

This is a screen capture of the exact moment when a 404 link is clicked. The issue is of course far more pronounced on real world pages with much bigger CSS files:

![image](https://user-images.githubusercontent.com/6329543/225606478-5d9ec3bf-6928-4e38-8a77-36908e70d3c0.png)

**Comment by daftspunk** [comment]
Hi @acasar 

This occurs because error 404's and 500s renders an error (https://github.com/octobercms/ajax/blob/main/src/turbo/error-renderer.js) instead of a snapshot. The error renderer replaces the entire head and body, so the scripts and stylesheets are completely replaced i.e: styles flash, javascript runs again.

The reason is anticipating page contents from a non-October application, such as Cloudflare, from the webserver, another application, or October's debug exception page.

**Comment by daftspunk** [comment]
A fix has been added here: https://github.com/octobercms/ajax/commit/8c846212e3371d561f757eba76aabf2cb11b2ccf

To bypass the error renderer, you can include the following meta tag in your error pages:

```
<meta name="turbo-visit-control" content="error">
```

This will trigger the snapshot render workflow and keep the head contents intact.

**Comment by daftspunk** [comment]
Fix has been published in v3.2.23 and documented here: https://github.com/octobercms/docs/commit/5b29d7efc64c68a1167955af874ac4b0452df5a5

Hopefully it helps!

**Comment by acasar** [comment]
@daftspunk Thanks 👍  I tested on some of our sites and it works perfectly.
