### ISSUE TITLE
Hot controls initialize twice

### ISSUE THREAD

**Issue by Metallizzer** [octobercms/ajax#29]
Hello.
octobercms@1.3.1 from npm

Hot controls initialize twice after second page load via pjax
Example:

```html
title = "Playground"
url = "/playground"
==
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Playground</title>
        <!-- data-turbo-eval="false" doesn't matter -->
        <script src="{{ mix('js/playground.js') }}" data-turbo-eval="false"></script>
    </head>
    <body>
        <a href="{{ this.id|page }}">Reload</a>
        <div data-control="playground">Playground</div>
    </body>
</html>
```

playground.js
```javascript
require("octobercms/src/framework-bundle");

console.log("This fires once");

oc.registerControl(
    "playground",
    class extends oc.ControlBase {
        init() {
            console.log("Init", Math.floor(Date.now() / 1000));
        }

        connect() {
            console.log("Connect", Math.floor(Date.now() / 1000));
        }

        disconnect() {
            console.log("Disconnect", Math.floor(Date.now() / 1000));
        }
    }
);

addEventListener("page:click", function (e) {
    console.log("Click Reload link");
});
```
![image](https://github.com/octobercms/ajax/assets/691719/dd0865f0-7d25-47b2-8fa5-93d6b080a542)
It can be seen from the log that after the second click on the link, the "init, connect and disconnect" methods are run twice, before the request is loaded and after

**Comment by daftspunk** [comment]
Hi @Metallizzer 

To take a guess at this, it is likely the result of the snapshot cache. When you click a link that has been visited before:

1. A cached snapshot is rendered
1. Hot controls will initialize (1)
1. The page is requested
1. The latest page is rendered
1. Hot controls will initialize (2)

You should not be too worried about this life cycle. Hot controls are performant and reliable; they are so fast they even avoid FOUC. Just be sure that controls are idempotent and perform the necessary garbage collection on disposal.

If it bothers you and you want to stop this, adjust the cache to remove the `data-control` tags so that when the snapshot is rendered, the hot controls do not initialize. See this event: https://docs.octobercms.com/3.x/cms/ajax/turbo-router.html#listening-for-the-cache-event

**Comment by Metallizzer** [comment]
Hi @daftspunk 

Yes, now I see that this issue is related to the rendering of cached content.
Adding the ```<meta name="turbo-cache-control" content="no-cache">``` tag to the entire page fixes this behavior.

> If it bothers you and you want to stop this, adjust the cache to remove the data-control tags so that when the snapshot is rendered, the hot controls do not initialize. See this event: https://docs.octobercms.com/3.x/cms/ajax/turbo-router.html#listening-for-the-cache-event

Thanks, I'll take a look at this.
Sometimes this can take a long time during initialization, for example when initializing sliders, carousels etc.

**Comment by daftspunk** [comment]
Another solution is to check this in the `connect()` function

```
if (document.documentElement.hasAttribute('data-turbo-preview')) {
    // Cached, don't do anything
}
```

Hope this helps!

**Comment by Metallizzer** [comment]
Thanks @daftspunk
